import { readFileSync } from "node:fs";
const s = JSON.parse(readFileSync("scripts/baseline-verify/secrets.json","utf8"));
const base="http://127.0.0.1:3000";
const tok = Object.fromEntries(s.tokens.map(t=>[t.name,t.raw]));
const login = async (e,p,l)=> (await (await fetch(base+"/api/v1/companion/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:e,password:p,label:l})})).json()).token;
const bisma = await login("bisma@nexus.local","demo-password-1234","probe-bind");
const zemnas = s.businesses.find(b=>b.key==="zemnas").id;
const lavish = s.businesses.find(b=>b.key==="lavish-foods").id;
const identity = s.identities[0].id;
console.log("== bind bisma ->", identity, s.identities[0].display_name);
let r = await fetch(base+"/api/v1/companion/bind",{method:"POST",headers:{authorization:`Bearer ${bisma}`,"content-type":"application/json"},body:JSON.stringify({installId:"probe-install-aaaa",identityId:identity,defaultBusinessId:zemnas,transfer:false})});
console.log(r.status, (await r.text()).slice(0,400));
console.log("== mcp submit_candidate (full token) ==");
r = await fetch(base+"/api/v1/mcp",{method:"POST",headers:{authorization:`Bearer ${tok["baseline-full"]}`,"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:1,method:"tools/call",params:{name:"nexus.submit_candidate",arguments:{business_id:zemnas,idempotency_key:"probe-cand-0001",full_name:"Probe Person",company_name:"Probe Co",job_title:"CTO"}}})});
console.log(r.status, (await r.text()).slice(0,700));
console.log("== mcp search_company (full token, proves read path) ==");
r = await fetch(base+"/api/v1/mcp",{method:"POST",headers:{authorization:`Bearer ${tok["baseline-full"]}`,"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:2,method:"tools/call",params:{name:"nexus.search_company",arguments:{business_id:zemnas,query:"Frame"}}})});
console.log(r.status, (await r.text()).slice(0,400));
console.log("== mcp create_signal (full token) ==");
r = await fetch(base+"/api/v1/mcp",{method:"POST",headers:{authorization:`Bearer ${tok["baseline-full"]}`,"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:3,method:"tools/call",params:{name:"nexus.create_signal",arguments:{business_id:zemnas,idempotency_key:"probe-sig-0001",kind:"hiring",polarity:"positive",strength:10,label:"probe"}}})});
console.log(r.status, (await r.text()).slice(0,500));
